hf_api_key: null
hf_tokenizer_checkpoint: "gpt2"
api_key: "YOUR_KEY_HERE"
model_name: "gpt-3.5-turbo-0125"
logs_dir: "./data/baseline_smoke/logs"
save_dir: "./data/baseline_smoke/predictions-chatgpt3-2k"
summary_path: "./data/baseline_smoke/predictions-chatgpt3-2k/summary.json"
max_context_toks: 2000
limit: 5
strategy_name: "baseline_fixed_relevant_context"
skip_existing: true
